<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(SolutionDir)common.targets"/>
    <PropertyGroup>
        <AssemblyName>UnlimitedChestColours</AssemblyName>
        <RootNamespace>UnlimitedChestColours</RootNamespace>
        <Version>1.0.0</Version>
        <ModFolderName>UnlimitedChestColours</ModFolderName>
        <Title>UnlimitedChestColours</Title>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <Publicize Include="StardewModdingAPI"/>
        <Publicize Include="Stardew Valley"/>
        <Publicize Include="StardewValley.GameData"/>
    </ItemGroup>
</Project>